<?php 
$data = $this->getEditRecord();

print_r($data);
?>
<form method="get" action="">
	
<td><?php echo $item->getData('name'); ?></td>

	<label>Name </label>
	<input type="text" name="name"></input>
	<br>

	<label>Phone </label>
	<input type="text" name="phone"></input>
	<br>

	<label>Content </label>
	<input type="text" name="content"></input>
	<br>

	<label>Age </label>
	<input type="text" name="age"></input>
	<br>

	<input type="submit" name="submit" value="Submit"></input>
</form>